### ISSUE TITLE
Doesn't support multibyte characters

### ISSUE THREAD

**Issue by chepner** [declaresub/abnf#1]
I'm working with https://github.com/dhall-lang/dhall-lang/blob/master/standard/dhall.abnf, which supports various non-ASCII Unicode characters, e.g. `combine       = %x2227 / "/\"`.

Currently, this raises an error, due to the use of `bytearray` in converting `%x2227` to a string. I believe the fix may be as simple as something like

```
def _decode_bytes(self, data, base):
        """Decodes num-val byte data. Intended to be private."""
       - return bytearray([int(data, base=base)]).decode(self.encoding)
       + return chr(int(data, base=base)) 
```

With this change,

```
>>> Rule.create('combine = %x2227 / "/\"')
<abnf.parser.Rule object at 0x10f4c1518>
>>> Rule('combine').parse("/\\")
(<abnf.parser.Node object at 0x10f48be48>, 1)
>>> x = Rule('combine').parse("∧")
>>> x[0].value
'∧'
```

**Comment by declaresub** [comment]
I have pushed a fix.  You might try it for yourself before I upload a new package to pypi.
