### ISSUE TITLE
Feature request: read from an abnf file

### ISSUE THREAD

**Issue by chepner** [declaresub/abnf#2]
I would like to parse all the rules found in  https://github.com/dhall-lang/dhall-lang/blob/master/standard/dhall.abnf at once. My first attempt was with something like

```
with open("dhall.abnf", newline='') as f:
    contents = f.read()
    rules = re.split(r'\r\n\r\n', contents)

for rule in enumerate(rules):
    processed_rule = ... # strip comments and ignore subsequently empty rules
    Rule.create(processed_rule)
```

This naive approach didn't work, as there are several rules *not* separated by blank lines.

Would it be possible to either add a `from_file` class method, or generalize `create` to support something like

```
Rule.create(r'''; NOTE: There are many line endings in the wild
;
; See: https://en.wikipedia.org/wiki/Newline
;
; For simplicity this supports Unix and Windows line-endings, which are the most
; common
end-of-line =
      %x0A     ; "\n"
    / %x0D.0A  ; "\r\n"

; This rule matches all characters that are not:
;
; * not ASCII
; * not part of a surrogate pair
; * not a "non-character"
valid-non-ascii =
      %x80-D7FF
    ; %xD800-DFFF = surrogate pairs
    / %xE000-FFFD
    ; %xFFFE-FFFF = non-characters
    / %x10000-1FFFD''')
```

which would add two rules `end-of-line` and `valid-non-ascii` at once. I realize the above is missing the `\r\n` line endings dictated by ABNF; I was hoping that `create` could add them back similar to how it will append a `\r\n` if the string doesn't already end with one.

The end result would be the creation of a separate `Rule` instance for each grammar rule found in the given ABNF file.

A related issue would be the need to handle comment-only lines.

**Comment by chepner** [comment]
Actually, since my anticipated use would be something like 

    with open("dhall.abnf") as f:
        Rule.create(f.read())  # CRLF line endings are present in the argument

there's less need to supply CRLF if LF alone is used. For testing or simple grammars, being explicit

    Rule.create('''; my grammar\r
    foo = "1"\r
    bar= "2"''')

would suffice.

**Comment by declaresub** [comment]
Your request is an obvious hole in the interface, and you've offered a good example, as the contents of dhall.abnf can be parsed as an ABNF rulelist.

So I suggest a class method from_file(path: typing.Union(str, pathlib.Path)) -> None which supposes that the contents of path is an ABNF rulelist.  It would parse the rulelist and add the rules therein to the class.

I don't know that we want to attempt to outguess file creators with regard to line breaks.

I should also note that dhall.abnf mentions various expectations of the parser that mine may or may not meet.  These might end up driving another feature request.

**Comment by declaresub** [comment]
As it turns out, dhall.abnf is not quite valid ABNF; unicode > 127 characters in comments are a problem.

**Comment by chepner** [comment]
I did miss that `rulelist` was a rule defined by `ABNFGrammarRule`, and was able to use that to define something very similar to `create`:

```
class Dhall(Rule):
    pass

with open("dhall.abnf", newline='') as f:
    contents = f.read()
parse_tree, start = ABNFGrammarRule("rulelist").parse(contents)
visitor = ABNFGrammarRuleNodeVisitor(Dhall)
visitor.visit(parse_tree)
for c in parse_tree.children:  # I think this loop would be vist_rulelist
    visitor.visit(c)
```

Having done that, I can write

```
node, _ = Dhall('complete-expression').parse('let x = 1 in x')
```

which produces *a* syntax tree, though not the correct one, likely due to the unmet expectations you mentioned.

**Comment by declaresub** [comment]
I have an implementation of from_file working.  I worked my way down through the grammar, and may see what is happening here.  Dhall('let-binding').parse('let x = 1 in x') consumes the entire source.  This appears to happen because the parser is not recognizing 'in' as a keyword.

**Comment by declaresub** [comment]
I believe I can deal with this situation by extending the parser to support negation and first-match alternation.  By adding this in, I was able to successfully parse the dhall examples I tried.

**Comment by declaresub** [comment]
Rule.from_file is implemented.
