### ISSUE TITLE
Handle prose-val if the rule exists?

### ISSUE THREAD

**Issue by mristin** [declaresub/abnf#6]
Hi,
Thank you a lot for implementing this library! It helps me tremendously to maintain regular expressions by compiling them from ABNFs.

I wondered if it would be possible to handle prose-vals in cases where the angle brackets are just used for cosmetics?

For example, in RFC 3987:
```
   ipath-empty    = 0<ipchar>
```

is just a more readable way to write:
```
ipath-empty    = 0ipchar
```

Please see also this related issue: https://github.com/katef/kgt/issues/10.

**Comment by declaresub** [comment]
I expect that this is possible.  Probably I should take a crack at adding such functionality as an option to see whether it makes sense.
